### ISSUE TITLE
Reimplement touch and gamepad controls

### ISSUE THREAD

**Issue by samuelbeepdev** [dragondungeonio/dragondungeon#22]

**Comment by samuelbeepdev** [comment]
Update: controlScheme variable now tracks whether user is on MnK or touch, with controller support coming soon. Still needs to be passed down through the component hierarchy to controls.

**Comment by RedFox360** [comment]
Still need to add buttons for turbo mode, fireballs, and zone capturing

**Comment by samuelbeepdev** [comment]
Don't ask about gamepad controls, they're never coming back.
